import { PokeTypes } from "../interface/poke-types";

const absolutePath = "/assets/poke-types/";

export const POKE_TYPES: PokeTypes[] = [
  {
    key: "completeTable",
    name: "Tabela Completa",
    path: "completeTable",
    disabled: true,
  },
  {
    key: "bug",
    name: "Inseto",
    path: "bug",
    disabled: true,
    img: `${absolutePath}bug.png`,
  },
  {
    key: "dark",
    name: "Sombrio",
    path: "dark",
    disabled: true,
    img: `${absolutePath}dark.png`,
  },
  {
    key: "dragon",
    name: "Dragão",
    path: "dragon",
    disabled: true,
    img: `${absolutePath}dragon.png`,
  },
  {
    key: "eletric",
    name: "Elétrico",
    path: "eletric",
    disabled: true,
    img: `${absolutePath}eletric.png`,
  },
  {
    key: "fairy",
    name: "Fada",
    path: "fairy",
    disabled: true,
    img: `${absolutePath}fairy.png`,
  },
  {
    key: "fighting",
    name: "Lutador",
    path: "fighting",
    disabled: true,
    img: `${absolutePath}fighting.png`,
  },
  {
    key: "fire",
    name: "Fogo",
    path: "fire",
    disabled: true,
    img: `${absolutePath}fyre.png`,
  },
  {
    key: "flying",
    name: "Voador",
    path: "flying",
    disabled: true,
    img: `${absolutePath}flying.png`,
  },
  {
    key: "ghost",
    name: "Fantasma",
    path: "ghost",
    disabled: true,
    img: `${absolutePath}ghost.png`,
  },
  {
    key: "grass",
    name: "Planta",
    path: "grass",
    disabled: true,
    img: `${absolutePath}grass.png`,
  },
  {
    key: "ground",
    name: "Terrestre",
    path: "ground",
    disabled: true,
    img: `${absolutePath}ground.png`,
  },
  {
    key: "ice",
    name: "Gelo",
    path: "ice",
    disabled: true,
    img: `${absolutePath}ice.png`,
  },
  {
    key: "normal",
    name: "Normal",
    path: "normal",
    disabled: true,
    img: `${absolutePath}normal.png`,
  },
  {
    key: "poison",
    name: "Venenoso",
    path: "poison",
    disabled: true,
    img: `${absolutePath}poison.png`,
  },
  {
    key: "psychic",
    name: "Psíquico",
    path: "psychic",
    disabled: true,
    img: `${absolutePath}psychic.png`,
  },
  {
    key: "rock",
    name: "Pedra",
    path: "rock",
    disabled: true,
    img: `${absolutePath}rock.png`,
  },
  {
    key: "steel",
    name: "Aço",
    path: "steel",
    disabled: true,
    img: `${absolutePath}steel.png`,
  },
  {
    key: "water",
    name: "Água",
    path: "water",
    disabled: true,
    img: `${absolutePath}water.png`,
  },
];
